USE employees;
# LIMIT AT THE END OF THE ORDER OF SQL OPERATIONS


# 10 VALUES ONLY OFFSET BY 10 ( first employee number is 10010 )
# COULD PROBABLY BE FOR PAGE OFFSET OF DATA BEING DISPLAYED OFFSET = CURR OFFSET + LIMIT (?)
SELECT * FROM employees
LIMIT 10 OFFSET 10;

SELECT * FROM employees
WHERE first_name LIKE '%e'
ORDER BY first_name
LIMIT 20;